// GENERATED BY gg_version WriteVersionFile - DO NOT EDIT.
// Kept in sync by test/dna_rljson_version.test.ts.

/** The version of the `@rljson/dna-rljson` package. */
export const dnaRljsonVersion = '0.2.0';
